name: Deploy API

on:
  workflow_dispatch:
  push:
    branches: ["dev"]
    tags: ["v*"]
    paths:
      - src/UserInterface/**
      - src/Core/**
      - .github/workflows/deploy-api.yml
  pull_request:
    branches: ["dev"]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: .NET Testing
        uses: ./.github/workflows/dotnet-testing.yaml@dev
        with:
          dotnet-version: 6.0.x
          ssh-path: /home/runner/work/houston/houston/src/UserInterface/Houston.API.UnitTests/bin/Debug/net6.0/PrivateKey.pem
        
      - name: Docker Login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Set image tags
        if: github.event_name != 'pull_request'
        id: tag
        run: |
          if [ "${{ startsWith(github.ref, 'refs/tags/') }}" = true ]; then
            echo "::set-output name=tag::${GITHUB_REF#refs/tags/},latest"
          else
            echo "::set-output name=tag::dev"
          fi
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: jpcarpanezi/houston-api:${{ steps.tag.outputs.tag }}
          file: src/UserInterface/Houston.API/Dockerfile
          context: ./
