name: Deploy Front

on:
  workflow_dispatch:
  push:
    branches: ["dev"]
    tags: ["v*"]
    paths:
      - src/Web/WebAngular/**
      - .github/workflows/deploy-front.yml
  pull_request:
    branches: ["dev"]
    paths:
      - src/Web/WebAngular/**
      - .github/workflows/deploy-front.yml
    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "src/Web/WebAngular"
    strategy:
      matrix:
        node-version: [18.x]
  
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm install --force
      - run: npm run build -- --production --if-present
      - run: npm test -- --configuration=ci
      
      - name: Docker Login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - name: Set image tags
        if: github.event_name != 'pull_request'
        id: tag
        run: |
          if [ "${{ startsWith(github.ref, 'refs/tags/') }}" = true ]; then
            echo "::set-output name=tag::${GITHUB_REF#refs/tags/},latest"
          else
            echo "::set-output name=tag::dev"
          fi
          
      - name: Build and push Docker images
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v2.7.0
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: jpcarpanezi/houston-front:${{ steps.tag.outputs.tag }}
          file: src/Web/WebAngular/Dockerfile
          context: ./
