name: .NET Testing

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
        default: 6.0.x
      ssh-path:
        required: true
        type: string
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Create testing private key
      run: ssh-keygen -t rsa -b 4096 -m PEM -N "" -f ${{ inputs.ssh-path }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
