name: .NET Pull request test

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Create testing private key
      run: ssh-keygen -t rsa -b 4096 -m PEM -N "" -f /src/UserInterface/Houston.API.UnitTests/PrivateKey.pem
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
